original_train_path: "../data/train.csv"
extra_train_path: "../data/lmsys-chatbot_arena_conversations-30k.csv"
use_both_train_and_extra: True
use_only_train: False
use_only_extra: False
train_data: "dataset/random_all_in_one_train.csv"
valid_data: "dataset/random_all_in_one_valid.csv"
resume_from_checkpoint: ""
all_in_one: True
prompt_type: 2
if_train: True
split: True
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
learning_rate: 2.0e-4
warmup_ratio: 0.1
num_train_epochs: 2
gradient_accumulation_steps: 16
logging_steps: 50
eval_steps: 300
save_steps: 300
weight_decay: 1.0e-3
use_8_bit_optimizer: True
MAX_INPUT: 3000
MODEL: "microsoft/Phi-3-mini-4k-instruct"
awp_lr: 0
awp_eps: 1.0e-4
awp_start_epoch: 1.0
label_smoothing_factor: 0
output_dir: "output"
use_cache: False
token_type: "MC"
lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
test_mode: False